# Generated by Django 6.0.3 on 2026-03-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserSessionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("sales_df_pickle", models.BinaryField(blank=True, null=True)),
                ("expenses_df_pickle", models.BinaryField(blank=True, null=True)),
                ("products", models.JSONField(default=list)),
                ("sales_months", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "simulator_user_session",
            },
        ),
    ]
