# Generated by Django 5.1.11 on 2026-06-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("name", models.CharField(max_length=120)),
                ("month", models.CharField(blank=True, default="", max_length=7)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("sales_df_pickle", models.BinaryField(blank=True, null=True)),
                ("expenses_df_pickle", models.BinaryField(blank=True, null=True)),
                ("products", models.JSONField(default=list)),
                ("sales_months", models.JSONField(default=list)),
                ("kpi_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "simulator_saved_scenario",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["session_key", "-updated_at"],
                        name="simulator_s_session_c756c3_idx",
                    )
                ],
            },
        ),
    ]
